version: "3.9"

services:
  backend:
    build: ./apps/backend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    env_file:
      - ./apps/backend/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - llama

  frontend:
    build: ./apps/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  llama:
    build: ./apps/llama-bridge
    volumes:
      - ./apps/llama-bridge:/app
      - ./apps/llama-bridge/chroma_db:/app/chroma_db
      - ./apps/llama-bridge/documents:/app/documents
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000" 